[package]
name = "raft_custom_test"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
bincode = "1.3.3"
log = "0.4.26"
simplelog = "0.12.2"
rand = "0.9.0"
socket2 = "0.5.8"
serde_json = "1.0.139"
